spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sell_on?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 0000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.mapstruct: DEBUG

